/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Login (void);
GtkWidget* create_Administrateur (void);
GtkWidget* create_Donneur (void);
GtkWidget* create_Responsable_en_Ets (void);
GtkWidget* create_gestion_des_dons (void);
GtkWidget* create_gestion_des_fiches_donneurs (void);
GtkWidget* create_window4 (void);
